language: cpp

cache: ccache

sudo: false

compiler:
 - gcc

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libqt5core5a
    - libqt5network5
    
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - export CTEST_OUTPUT_ON_FAILURE=1
 - make test
