language: cpp

cache: ccache

sudo: false

compiler:
 - gcc

addons:
  apt:
    packages:
    - cmake
    - ppa:beineri/opt-qt551
    
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - export CTEST_OUTPUT_ON_FAILURE=1
 - make test
